package entidades;
// Generated 14/09/2016 08:51:44 by Hibernate Tools 4.3.1



/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int idCli;
     private String nome;
     private String endereco;
     private String telefone;
     private String email;

    public Cliente() {
    }

	
    public Cliente(int idCli) {
        this.idCli = idCli;
    }
    public Cliente(int idCli, String nome, String endereco, String telefone, String email) {
       this.idCli = idCli;
       this.nome = nome;
       this.endereco = endereco;
       this.telefone = telefone;
       this.email = email;
    }
   
    public int getIdCli() {
        return this.idCli;
    }
    
    public void setIdCli(int idCli) {
        this.idCli = idCli;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


