package entidades;
// Generated 14/09/2016 08:51:44 by Hibernate Tools 4.3.1



/**
 * Produto generated by hbm2java
 */
public class Produto  implements java.io.Serializable {


     private int idProd;
     private String nome;
     private String marca;
     private Double preco;

    public Produto() {
    }

	
    public Produto(int idProd) {
        this.idProd = idProd;
    }
    public Produto(int idProd, String nome, String marca, Double preco) {
       this.idProd = idProd;
       this.nome = nome;
       this.marca = marca;
       this.preco = preco;
    }
   
    public int getIdProd() {
        return this.idProd;
    }
    
    public void setIdProd(int idProd) {
        this.idProd = idProd;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public Double getPreco() {
        return this.preco;
    }
    
    public void setPreco(Double preco) {
        this.preco = preco;
    }




}


